spring:
  profiles:
    active: ${profile:dev}

# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# 不走拦截器的url
web:
  exclude:
    path: /login/**,/test/**,/verifyCode,/register,/changePass,/forgot

---
#本地开发环境
# 数据库相关配置
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.local:3306/test?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  redis:
    host: local.local
    port: 6379
    timeout: 3000
  http:
    multipart:
      max-file-size: 5000Mb
      max-request-size: 5000Mb

web:
  var:
    forgot: http://localhost:8081/change.html?id=
    share: http://localhost:8081/share.html?code=
    filePath: /Users/zhangpengzhi/WebstormProjects/static/
    splitPath: static/
    pageSize: 10


---
#服务器生产环境
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.183.161:3306/test?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  redis:
    host: 106.15.183.161
    port: 6379
    timeout: 3000
    password: root
  http:
    multipart:
      max-file-size: 5000Mb
      max-request-size: 5000Mb

web:
  var:
    forgot: http://106.15.183.161/change.html?id=
    share: http://106.15.183.161/share.html?code=
    filePath: /online-disk/static/
    splitPath: static/
    pageSize: 10

#生产环境日志路径
logging:
  file: /online-disk/out.log
