# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.189.131:3306/test?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  redis:
    host: 172.16.189.131
    port: 6379
    timeout: 3000
  http:
    multipart:
      max-file-size: 5000Mb
      max-request-size: 5000Mb


# 不走拦截器的url
music:
  exclude:
    path: /login/**,/test,/verifyCode,/register,/changePass,/forgot,/file/**

web:
  var:
    forgot: http://172.16.42.99:8081/change.html?id=