spring:
  profiles:
    active: ${profile:pro}

# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# 不走拦截器的url
music:
  exclude:
    path: /login/**,/test/**,/verifyCode,/register,/changePass,/forgot

---
#本地开发环境
# 数据库相关配置
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.189.131:3306/test?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  redis:
    host: 172.16.189.131
    port: 6379
    timeout: 3000
  http:
    multipart:
      max-file-size: 5000Mb
      max-request-size: 5000Mb

web:
  var:
    forgot: http://172.16.189.131:8080/change.html?id=
    filePath: /Users/zhangpengzhi/WebstormProjects/online-disk-front/static/
    splitPath: online-disk-front/


---
#服务器生产环境
spring:
  profiles: pro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.183.161:3306/pan?useUnicode=true&characterEncoding=utf-8
    password: root
    username: root
  redis:
    host: 106.15.183.161
    port: 6379
    timeout: 3000
    password: root
  http:
    multipart:
      max-file-size: 5000Mb
      max-request-size: 5000Mb

web:
  var:
    forgot: http://106.15.183.161/change.html?id=
    filePath: /online-disk/static/
    splitPath: static/

#生产环境日志路径
logging:
  file: /online-disk/out.log
