# mybatis相关配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

# 数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.com:3306/test
    password: root
    username: root
  redis:
    host: local.com
    port: 6379
    timeout: 3000

# 不走拦截器的url
music:
  exclude:
    path: /login/**,/test/**,/verifyCode,/register